server:
  port: 800
  servlet: 
    session:
      timeout: 7200 
      
spring:
  application:
    name: nginx配置器
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  devtools:
    restart:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jmx:
    enabled: true 
  database: 
    type: mysql
    package: com.cym.model
  datasource:
    url: jdbc:mysql://10.39.3.92:3306/test
    username: root
    password: 1qaz2wsx
    
logging: 
  level: 
    root: info

custom:
  nginx: E:/nginx-1.17.10/conf/nginx.conf
  admin:
    name: admin
    pass: admin